### ISSUE TITLE
your

### ISSUE THREAD

**Issue by AhoyLemon** [AhoyLemon/greatsex.tips#14]
![image](https://user-images.githubusercontent.com/3413200/37549455-3f17a2be-294e-11e8-809f-6570e1e00733.png)
wrong

**Comment by SanguinaryNovel** [comment]
What? Is that the wrong Wu-Tang secret?

**Comment by SanguinaryNovel** [comment]
We're not going to talk about how it took me at least 20 times of reading this to figure out what the actual problem was.
